name: Deploy

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  deploy:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    env:
      IMAGE_VERSION: ${{ github.run_number }}

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configurar TAG
        run: echo "IMAGE_VERSION=$(date +%s)" >> $GITHUB_ENV

      - name: Construir e enviar imagem
        run: |
          docker build -t uken49/reconhece-lixo:${{ env.IMAGE_VERSION }} -t uken49/reconhece-lixo:latest .
          docker push uken49/reconhece-lixo:${{ env.IMAGE_VERSION }}
          docker push uken49/reconhece-lixo:latest

      - name: Deploy na EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Parando container antigo..."
            docker stop reconhece-lixo || true
            docker rm reconhece-lixo || true

            echo "Baixando nova imagem..."
            docker pull uken49/reconhece-lixo:latest

            echo "Subindo container atualizado..."
            docker run -d \
              --name reconhece-lixo \
              --restart=unless-stopped \
              -p 80:80 \
              uken49/reconhece-lixo:latest

            echo "Deploy conclu√≠do!"